START_OF_UTTERANCE = '[START_OF_UTTERANCE]'
END_OF_PREFIX = '[END_OF_PREFIX]'
START_OF_CONTEXT = '[START_OF_CONTEXT]'
START_OF_TAG = '[START_OF_TAG]'

SPECIAL_TOKENS = [START_OF_UTTERANCE, END_OF_PREFIX, START_OF_CONTEXT, START_OF_TAG]
